steps:
  - input: ":video_game: How to play?"
    key: mode
    fields:
      - select: Game mode
        key: mode
        options:
          - label: Prompt me for every move
            value: manual
          - label: Choose moves completely at random
            value: random
          - label: Let Claude run the show
            value: ai

  - label: ":rage4: Run Doom"
    key: run-doom
    depends_on: mode
    plugins:
      - docker-compose#v5.10.0:
          run: doom-game
          mount-buildkite-agent: true
          propagate-environment: true
          environment:
            - ANTHROPIC_API_KEY
            - BUILDKITE_API_TOKEN
            - DOOM_MODE
