steps:
  - input: ":video_game: How to play?"
    key: mode
    fields:
      - select: Game mode
        key: mode
        options:
          - label: Manual (choose each move)
            value: manual
          - label: Random moves
            value: random
          - label: AI moves
            value: ai

  - label: ":rage4: Run Doom"
    depends_on: mode
    command: "./run-doom.sh"
