steps:
  - input: ":video_game: Select game mode"
    key: mode
    fields:
      - select: Game mode
        key: game_mode
        options:
          - label: 👆 Let me decide each move
            value: manual
          - label: 🎲 Randomly decide each move
            value: random
          - label: 🤖 Let AI decide each move
            value: ai

  - label: ":rage4: Run Doom"
    key: run-doom
    depends_on: mode
    command: "./run-doom.sh"
