steps:
  - input: ":video_game: How to play?"
    key: mode
    fields:
      - select: Game mode
        key: mode
        options:
          - label: Prompt me for every move
            value: manual
          - label: Choose moves completely at random
            value: random
          - label: Let Claude run the show
            value: ai

  - label: ":rage4: Run Doom"
    depends_on: mode
    plugins:
      - docker-compose#v5.10.0:
          run: doom-game
          command: ["./doom.rb"]
          mount-buildkite-agent: true
          environment:
            - ANTHROPIC_API_KEY
