steps:
  - label: ":rage4: Run Doom"
    key: run-doom
    plugins:
      - docker-compose#v5.10.0:
          run: doom
          propagate-environment: true
    timeout_in_minutes: 60

  - input: ":video_game: Select game mode"
    key: mode
    fields:
      - select: "Game mode"
        key: game_mode
        required: true
        options:
          - label: "🧑 Let me decide each action"
            value: "manual"
          - label: "🎲 Randomly decide each action"
            value: "random"
          - label: "🤖 Let AI decide each action"
            value: "ai"
      - select: "Level"
        key: level
        required: true
        default: "1"
        options:
          - label: "🏭 E1M1: Hangar"
            value: "1"
          - label: "☢️ E1M2: Nuclear Plant"
            value: "2"
          - label: "🧪 E1M3: Toxin Refinery"
            value: "3"
          - label: "🖥️ E1M4: Command Control"
            value: "4"
          - label: "🔬 E1M5: Phobos Lab"
            value: "5"
          - label: "⚙️ E1M6: Central Processing"
            value: "6"
          - label: "💻 E1M7: Computer Station"
            value: "7"
          - label: "🌌 E1M8: Phobos Anomaly"
            value: "8"
          - label: "🪖 E1M9: Military Base"
            value: "9"
