steps:
  - label: "🎮 DOOM Game"
    commands:
      - "sudo apt-get update && sudo apt-get install -y xvfb xdotool ffmpeg chocolate-doom curl unzip"
      - "./doom_simple.rb"
    env:
      DISPLAY: ":99"
    agents:
      queue: "default"
